#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$1" in
    help | apcaccess:help)
        help_content_func() {
            declare desc="return help_content string"
            cat<<help_content
        apcaccess, Gives APC UPS information
help_content
        }

        if [[ $1 = "apcaccess:help" ]]; then
            echo -e 'Usage: dokku apcaccess [<app>]'
            echo ''
            echo 'Give APC UPS information'
            echo ''
            echo 'Example:'
            echo ''
            echo '$ dokku apcaccess'
        else
            help_content_func
        fi
        ;;

    *)
        exit $DOKKU_NOT_IMPLEMENTED_EXIT
        ;;
esac

